### ISSUE TITLE
travis-ci

### ISSUE THREAD

**Issue by persianpros** [PLi-metas/enigma2-openpli-fulan#6]
I did add the needed headers for travis-ci checks but still it gives error: https://travis-ci.org/PLi-metas/enigma2-openpli-fulan/builds/432187260?utm_source=github_status&utm_medium=notification

**Comment by kueken** [comment]
I would say you have deleted too much.
The lines starting from 'package' should all stay in it.

But I really do not know that much.

**Comment by persianpros** [comment]
We don't need gcc 4 and 5 that's why I deleted those ...

**Comment by kueken** [comment]
This image is built with gcc4.9.4 ;-)

**Comment by persianpros** [comment]
Oops I didn't see https://github.com/PLi-metas/meta-fulan/blob/develop/conf/machine/include/oem-fulan.inc#L15

**Comment by kueken** [comment]
I just made it, I have to test.
The bugs point to VFD

**Comment by kueken** [comment]
OK
Building here is flawless

**Comment by persianpros** [comment]
As you mentioned pti, is it ok? Did you test it yourself?

**Comment by kueken** [comment]
I do not have a smartcard, but can tell by size.
The pti should work properly.
Now you have to hope for feedback from users.

In the pli forum they have exchanged incorrectly and even that has apparently worked.
As I said I can only see the size of the pti and activation of the Cam in the menu, but not really test.

**Comment by kueken** [comment]
Does the building work again with you?
Here it builds easily, without errors.

**Comment by persianpros** [comment]
The build was fine, I want to have travis like PLi has green checks: https://github.com/OpenPLi/enigma2/commits/develop

**Comment by kueken** [comment]
Believe that in the pti.ko but what is not right.
Can the spark7162 no longer operate with the remote control.

**Comment by persianpros** [comment]
Maybe the problem is in https://github.com/PLi-metas/enigma2-openpli-fulan/blob/master/lib/gdi/fb.cpp or https://github.com/PLi-metas/enigma2-openpli-fulan/blob/master/lib/gdi/fb.h

**Comment by MastaG** [comment]
I haven't used trivus-ci yet, but I'm going to revert the inclusion of driver headers inside the enigma2-openpli-fulan repository.
The driver headers should be provided by the fulan-dvb-modules and libmme-image packages.

In OE all headers will be staged to a temporary sysroot from all packages which are added to DEPENDS.

**Comment by persianpros** [comment]
That's ok but please add the needed depends so we could use travis-ci :)

**Comment by MastaG** [comment]
After looking a bit further into Travis-ci, it's pointless.
First of all it builds with gcc-7 for x86-64 instead of sh4.
See: 1788checking build system type... x86_64-unknown-linux-gnu
1789checking host system type... x86_64-unknown-linux-gnu

The code inside enigma2-openpli-fulan is full of:
#ifdef __sh__
Which is a gcc system macro for defining the SuperH architecture.

So it doesn't represent a test-case whether the code is running fine on sh4 cpu's at all.
All it can tell you is whether you made a typo or fuckup somewhere in the C++ code.

And since I'd like to test out different drivers with different headers, I don't want to see headers from a specific driver added to the enigma2-openpli-fulan repository.

I'm going to revert them to keep things clean.
If you really want your travis-ci build to succeed then please add a sh4_headers.tar.gz package somewhere and it to your build-job so it gets extracted to the source code directory on building.
This way it only applied to travis-ci.

But please don't start modifying code (or python plugins) to try and build them for x86_64.. really thats stupid.. since it was made to run on sh4 ;)

**Comment by persianpros** [comment]
Ok seems logical, I just restored the master to what was before, please merge the latest changes with PLi.

Thanks in advance.
